// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/jiebutech/geoip/app/api"
	"github.com/jiebutech/geoip/pkg/geoip"
)

// Injectors from wire.go:

func NewGeoIpController() *api.GeoIpCtrl {
	geopIpSvc := geoip.NewGeoIpService()
	geoIpCtrl := api.NewGeoIpController(geopIpSvc)
	return geoIpCtrl
}
